### ISSUE TITLE
Incorrect NeedsCompilation

### ISSUE THREAD

**Issue by Enchufa2** [gavinsimpson/analogueExtra#1]
The package declares `NeedsCompilation: yes` in the DESCRIPTION file, but it does not compile anything.

**Comment by gavinsimpson** [comment]
Thanks; this is likely the result of a copy paste from the `DESCRIPTION` of **analogue** when I created this package offshoot.

**Comment by gavinsimpson** [comment]
This is now fixed; I'll see when I get round to releasing it to CRAN.
